name: Nexrender server build binary

on:
  push:
    branches: [ $default-branch, "feature/refactor-nexrender-server" ]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run install-child
            - run: npm run start
            - run: npm test

    build:
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run install-child
            - run: npm run pkg
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: refactor-nexrender
                  release_name: Release refactor-nexrender
                  draft: false
                  prerelease: false
            - name: Upload Release Asset Linux
              id: upload-release-linux
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
                  asset_path: ./bin/nexrender-server-linux
                  asset_name: nexrender-server-linux
                  asset_content_type: application/octet-stream
            - name: Upload Release Asset Windows
              id: upload-release-windows
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./bin/nexrender-server-win64.exe
                  asset_name: nexrender-server-win64.exe
                  asset_content_type: application/octet-stream
